"""network-policy

Revision ID: cab701a1c3e6
Revises: 
Create Date: 2019-04-10 20:18:23.517000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab701a1c3e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('namespace', sa.String(length=64), nullable=True),
    sa.Column('cidr', sa.String(length=64), nullable=True),
    sa.Column('excepts', sa.String(length=64), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=64), nullable=True),
    sa.Column('project', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('spec_pod', sa.String(length=64), nullable=True),
    sa.Column('policy_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_policy_cidr'), 'network_policy', ['cidr'], unique=True)
    op.create_index(op.f('ix_network_policy_excepts'), 'network_policy', ['excepts'], unique=True)
    op.create_index(op.f('ix_network_policy_name'), 'network_policy', ['name'], unique=True)
    op.create_index(op.f('ix_network_policy_namespace'), 'network_policy', ['namespace'], unique=True)
    op.create_index(op.f('ix_network_policy_policy_type'), 'network_policy', ['policy_type'], unique=True)
    op.create_index(op.f('ix_network_policy_port'), 'network_policy', ['port'], unique=True)
    op.create_index(op.f('ix_network_policy_project'), 'network_policy', ['project'], unique=True)
    op.create_index(op.f('ix_network_policy_protocol'), 'network_policy', ['protocol'], unique=True)
    op.create_index(op.f('ix_network_policy_role'), 'network_policy', ['role'], unique=True)
    op.create_index(op.f('ix_network_policy_spec_pod'), 'network_policy', ['spec_pod'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_policy_spec_pod'), table_name='network_policy')
    op.drop_index(op.f('ix_network_policy_role'), table_name='network_policy')
    op.drop_index(op.f('ix_network_policy_protocol'), table_name='network_policy')
    op.drop_index(op.f('ix_network_policy_project'), table_name='network_policy')
    op.drop_index(op.f('ix_network_policy_port'), table_name='network_policy')
    op.drop_index(op.f('ix_network_policy_policy_type'), table_name='network_policy')
    op.drop_index(op.f('ix_network_policy_namespace'), table_name='network_policy')
    op.drop_index(op.f('ix_network_policy_name'), table_name='network_policy')
    op.drop_index(op.f('ix_network_policy_excepts'), table_name='network_policy')
    op.drop_index(op.f('ix_network_policy_cidr'), table_name='network_policy')
    op.drop_table('network_policy')
    # ### end Alembic commands ###
